import {
  ActivityAction,
  CustomerStatus,
  InventoryCategory,
  InventoryStatus,
  IssueCategory,
  IssueStatus,
  Prisma,
  Priority,
  TeamMemberStatus,
  TeamRole,
  WorkItemKind,
  WorkItemStatus,
} from "../src/generated/prisma/client";

const atNoonUtc = (date: string) => new Date(`${date}T12:00:00.000Z`);

const collectSeedIds = <T extends { id?: string }>(records: T[]): string[] =>
  records.map(({ id }) => {
    if (!id) {
      throw new Error("Every demo seed record must define a stable id.");
    }

    return id;
  });

export const DEMO_SEED_LABEL = "OpsPilot demo seed data";
export const DEMO_REFERENCE_DATE = atNoonUtc("2026-07-07");

export const teamMembers: Prisma.TeamMemberCreateManyInput[] = [
  {
    id: "team-olivia-chen",
    name: "Olivia Chen",
    email: "olivia.chen@opspilot-demo.test",
    role: TeamRole.OPERATIONS_MANAGER,
    status: TeamMemberStatus.ACTIVE,
    createdAt: atNoonUtc("2026-05-28"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "team-marcus-reed",
    name: "Marcus Reed",
    email: "marcus.reed@opspilot-demo.test",
    role: TeamRole.ADMIN_STAFF,
    status: TeamMemberStatus.ACTIVE,
    createdAt: atNoonUtc("2026-05-28"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "team-sofia-patel",
    name: "Sofia Patel",
    email: "sofia.patel@opspilot-demo.test",
    role: TeamRole.SUPPORT_STAFF,
    status: TeamMemberStatus.ACTIVE,
    createdAt: atNoonUtc("2026-05-29"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "team-daniel-kim",
    name: "Daniel Kim",
    email: "daniel.kim@opspilot-demo.test",
    role: TeamRole.QA_ENGINEER,
    status: TeamMemberStatus.ACTIVE,
    createdAt: atNoonUtc("2026-05-30"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "team-ava-morgan",
    name: "Ava Morgan",
    email: "ava.morgan@opspilot-demo.test",
    role: TeamRole.DEVELOPER,
    status: TeamMemberStatus.ACTIVE,
    createdAt: atNoonUtc("2026-06-02"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "team-elena-roberts",
    name: "Elena Roberts",
    email: "elena.roberts@opspilot-demo.test",
    role: TeamRole.BUSINESS_OWNER,
    status: TeamMemberStatus.INACTIVE,
    createdAt: atNoonUtc("2026-06-03"),
    updatedAt: atNoonUtc("2026-07-01"),
    archivedAt: atNoonUtc("2026-07-01"),
  },
];

export const customers: Omit<Prisma.CustomerCreateManyInput, "workspaceId">[] = [
  {
    id: "cust-northstar-outfitters",
    name: "Northstar Outfitters Demo",
    contactName: "Maya Chen",
    email: "maya.chen@northstar-demo.test",
    phone: "555-0101",
    status: CustomerStatus.ACTIVE,
    ownerId: "team-olivia-chen",
    notes: "Demo seed data: active retail account with device rollout and campaign work.",
    createdAt: atNoonUtc("2026-06-01"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "cust-harborview-dental",
    name: "Harborview Dental Demo",
    contactName: "Jon Bell",
    email: "jon.bell@harborview-demo.test",
    phone: "555-0102",
    status: CustomerStatus.ACTIVE,
    ownerId: "team-marcus-reed",
    notes: "Demo seed data: service account waiting on reminder copy approval.",
    createdAt: atNoonUtc("2026-06-02"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "cust-cityline-fitness",
    name: "Cityline Fitness Demo",
    contactName: "Rina Torres",
    email: "rina.torres@cityline-demo.test",
    phone: "555-0103",
    status: CustomerStatus.ACTIVE,
    ownerId: "team-sofia-patel",
    notes: "Demo seed data: active customer with kiosk and QA follow-up work.",
    createdAt: atNoonUtc("2026-06-03"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "cust-brightpath-learning",
    name: "BrightPath Learning Demo",
    contactName: "Theo Grant",
    email: "theo.grant@brightpath-demo.test",
    phone: "555-0104",
    status: CustomerStatus.ACTIVE,
    ownerId: "team-marcus-reed",
    notes: "Demo seed data: education account with completed launch work.",
    createdAt: atNoonUtc("2026-06-04"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "cust-greenfield-market",
    name: "Greenfield Market Demo",
    contactName: "Amara Lewis",
    email: "amara.lewis@greenfield-demo.test",
    phone: "555-0105",
    status: CustomerStatus.ACTIVE,
    ownerId: "team-olivia-chen",
    notes: "Demo seed data: operations account with SKU and inventory cleanup work.",
    createdAt: atNoonUtc("2026-06-05"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "cust-summit-wireless-lab",
    name: "Summit Wireless Lab Demo",
    contactName: "Noah Singh",
    email: "noah.singh@summitwireless-demo.test",
    phone: "555-0106",
    status: CustomerStatus.ACTIVE,
    ownerId: "team-ava-morgan",
    notes: "Demo seed data: technical account for test devices and demo accounts.",
    createdAt: atNoonUtc("2026-06-06"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "cust-lakeside-events",
    name: "Lakeside Events Demo",
    contactName: "Priya Shah",
    email: "priya.shah@lakeside-demo.test",
    phone: "555-0107",
    status: CustomerStatus.PROSPECT,
    ownerId: "team-sofia-patel",
    notes: "Demo seed data: prospect with draft quote and registration planning.",
    createdAt: atNoonUtc("2026-06-10"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "cust-bluepeak-nonprofit",
    name: "BluePeak Nonprofit Demo",
    contactName: "Evan Brooks",
    email: "evan.brooks@bluepeak-demo.test",
    phone: "555-0108",
    status: CustomerStatus.ACTIVE,
    ownerId: "team-olivia-chen",
    notes: "Demo seed data: nonprofit campaign account with urgent blocked reporting work.",
    createdAt: atNoonUtc("2026-06-12"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "cust-metro-print-studio",
    name: "Metro Print Studio Demo",
    contactName: "Leah Wright",
    email: "leah.wright@metroprint-demo.test",
    phone: "555-0109",
    status: CustomerStatus.PAUSED,
    ownerId: "team-marcus-reed",
    notes: "Demo seed data: paused account with cancelled portal work.",
    createdAt: atNoonUtc("2026-06-14"),
    updatedAt: atNoonUtc("2026-07-02"),
  },
  {
    id: "cust-clearsky-logistics",
    name: "ClearSky Logistics Demo",
    contactName: "Nadia Park",
    email: "nadia.park@clearsky-demo.test",
    phone: "555-0110",
    status: CustomerStatus.ARCHIVED,
    ownerId: "team-olivia-chen",
    notes: "Demo seed data: archived customer retained for reporting and archive-state checks.",
    createdAt: atNoonUtc("2026-06-16"),
    updatedAt: atNoonUtc("2026-07-01"),
    archivedAt: atNoonUtc("2026-07-01"),
  },
];

export const workItems: Omit<Prisma.WorkItemCreateManyInput, "workspaceId">[] = [
  {
    id: "work-northstar-spring-launch",
    title: "Spring launch campaign setup",
    kind: WorkItemKind.CAMPAIGN,
    status: WorkItemStatus.ACTIVE,
    priority: Priority.HIGH,
    dueDate: atNoonUtc("2026-07-15"),
    estimatedValueCents: 1250000,
    customerId: "cust-northstar-outfitters",
    ownerId: "team-marcus-reed",
    notes: "Demo seed data: active campaign work for future campaign tables and filters.",
    createdAt: atNoonUtc("2026-06-18"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "work-northstar-pos-device-rollout",
    title: "POS device rollout",
    kind: WorkItemKind.ORDER,
    status: WorkItemStatus.ACTIVE,
    priority: Priority.URGENT,
    dueDate: atNoonUtc("2026-07-02"),
    estimatedValueCents: 840000,
    customerId: "cust-northstar-outfitters",
    ownerId: "team-ava-morgan",
    notes: "Demo seed data: overdue urgent work item for dashboard and issue-triage checks.",
    createdAt: atNoonUtc("2026-06-19"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "work-harborview-patient-reminders",
    title: "Patient reminder workflow",
    kind: WorkItemKind.SERVICE_REQUEST,
    status: WorkItemStatus.BLOCKED,
    priority: Priority.HIGH,
    dueDate: atNoonUtc("2026-07-05"),
    estimatedValueCents: 480000,
    customerId: "cust-harborview-dental",
    ownerId: "team-sofia-patel",
    notes: "Demo seed data: blocked service work waiting on customer approval.",
    createdAt: atNoonUtc("2026-06-20"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "work-cityline-membership-kiosk",
    title: "Membership kiosk installation",
    kind: WorkItemKind.ORDER,
    status: WorkItemStatus.ACTIVE,
    priority: Priority.MEDIUM,
    dueDate: atNoonUtc("2026-07-14"),
    estimatedValueCents: 950000,
    customerId: "cust-cityline-fitness",
    ownerId: "team-ava-morgan",
    notes: "Demo seed data: active installation with assigned hardware.",
    createdAt: atNoonUtc("2026-06-21"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "work-brightpath-enrollment-campaign",
    title: "Enrollment campaign closeout",
    kind: WorkItemKind.CAMPAIGN,
    status: WorkItemStatus.COMPLETED,
    priority: Priority.MEDIUM,
    dueDate: atNoonUtc("2026-07-04"),
    completedAt: atNoonUtc("2026-07-06"),
    estimatedValueCents: 670000,
    customerId: "cust-brightpath-learning",
    ownerId: "team-marcus-reed",
    notes: "Demo seed data: completed this week for dashboard completion metrics.",
    createdAt: atNoonUtc("2026-06-22"),
    updatedAt: atNoonUtc("2026-07-06"),
  },
  {
    id: "work-greenfield-inventory-sync",
    title: "Inventory sync planning",
    kind: WorkItemKind.SERVICE_REQUEST,
    status: WorkItemStatus.DRAFT,
    priority: Priority.MEDIUM,
    dueDate: atNoonUtc("2026-07-21"),
    estimatedValueCents: 390000,
    customerId: "cust-greenfield-market",
    ownerId: "team-daniel-kim",
    notes: "Demo seed data: draft work for draft-status filtering.",
    createdAt: atNoonUtc("2026-06-22"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "work-summit-test-device-setup",
    title: "Test device setup",
    kind: WorkItemKind.ORDER,
    status: WorkItemStatus.ACTIVE,
    priority: Priority.HIGH,
    dueDate: atNoonUtc("2026-07-10"),
    estimatedValueCents: 520000,
    customerId: "cust-summit-wireless-lab",
    ownerId: "team-ava-morgan",
    notes: "Demo seed data: technical setup work with test devices.",
    createdAt: atNoonUtc("2026-06-23"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "work-lakeside-event-registration",
    title: "Event registration quote",
    kind: WorkItemKind.SERVICE_REQUEST,
    status: WorkItemStatus.DRAFT,
    priority: Priority.LOW,
    dueDate: atNoonUtc("2026-07-28"),
    estimatedValueCents: 210000,
    customerId: "cust-lakeside-events",
    ownerId: "team-sofia-patel",
    notes: "Demo seed data: prospect quote still in draft.",
    createdAt: atNoonUtc("2026-06-24"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "work-bluepeak-donor-campaign",
    title: "Donor campaign segmentation",
    kind: WorkItemKind.CAMPAIGN,
    status: WorkItemStatus.BLOCKED,
    priority: Priority.URGENT,
    dueDate: atNoonUtc("2026-07-01"),
    estimatedValueCents: 760000,
    customerId: "cust-bluepeak-nonprofit",
    ownerId: "team-olivia-chen",
    notes: "Demo seed data: urgent blocked campaign for high-priority dashboard checks.",
    createdAt: atNoonUtc("2026-06-24"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "work-metro-print-reorder-portal",
    title: "Reorder portal cleanup",
    kind: WorkItemKind.SERVICE_REQUEST,
    status: WorkItemStatus.CANCELLED,
    priority: Priority.LOW,
    dueDate: atNoonUtc("2026-06-27"),
    estimatedValueCents: 310000,
    customerId: "cust-metro-print-studio",
    ownerId: "team-marcus-reed",
    notes: "Demo seed data: cancelled paused-account work for status filters.",
    createdAt: atNoonUtc("2026-06-25"),
    updatedAt: atNoonUtc("2026-07-02"),
  },
  {
    id: "work-clearsky-route-dashboard",
    title: "Route dashboard handoff",
    kind: WorkItemKind.SERVICE_REQUEST,
    status: WorkItemStatus.ACTIVE,
    priority: Priority.HIGH,
    dueDate: atNoonUtc("2026-07-09"),
    estimatedValueCents: 1020000,
    customerId: "cust-clearsky-logistics",
    ownerId: "team-daniel-kim",
    notes: "Demo seed data: active archived-customer example retained for reporting edge cases.",
    createdAt: atNoonUtc("2026-06-25"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "work-northstar-support-refresh",
    title: "Support playbook refresh",
    kind: WorkItemKind.SERVICE_REQUEST,
    status: WorkItemStatus.COMPLETED,
    priority: Priority.LOW,
    dueDate: atNoonUtc("2026-07-03"),
    completedAt: atNoonUtc("2026-07-03"),
    estimatedValueCents: 180000,
    customerId: "cust-northstar-outfitters",
    ownerId: "team-sofia-patel",
    notes: "Demo seed data: completed support work for recent activity context.",
    createdAt: atNoonUtc("2026-06-26"),
    updatedAt: atNoonUtc("2026-07-03"),
  },
  {
    id: "work-harborview-license-renewal",
    title: "License renewal pack",
    kind: WorkItemKind.ORDER,
    status: WorkItemStatus.ACTIVE,
    priority: Priority.MEDIUM,
    dueDate: atNoonUtc("2026-07-16"),
    estimatedValueCents: 420000,
    customerId: "cust-harborview-dental",
    ownerId: "team-marcus-reed",
    notes: "Demo seed data: renewal order with license inventory.",
    createdAt: atNoonUtc("2026-06-26"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "work-cityline-qa-bug-bash",
    title: "Kiosk QA bug bash",
    kind: WorkItemKind.SERVICE_REQUEST,
    status: WorkItemStatus.ACTIVE,
    priority: Priority.HIGH,
    dueDate: atNoonUtc("2026-07-08"),
    estimatedValueCents: 260000,
    customerId: "cust-cityline-fitness",
    ownerId: "team-daniel-kim",
    notes: "Demo seed data: QA-focused work item for issue workflow proof.",
    createdAt: atNoonUtc("2026-06-27"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "work-brightpath-asset-handoff",
    title: "Training asset handoff",
    kind: WorkItemKind.CAMPAIGN,
    status: WorkItemStatus.COMPLETED,
    priority: Priority.HIGH,
    dueDate: atNoonUtc("2026-07-07"),
    completedAt: atNoonUtc("2026-07-07"),
    estimatedValueCents: 330000,
    customerId: "cust-brightpath-learning",
    ownerId: "team-marcus-reed",
    notes: "Demo seed data: same-day completion for weekly completion checks.",
    createdAt: atNoonUtc("2026-06-28"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "work-greenfield-sku-cleanup",
    title: "SKU cleanup and barcode check",
    kind: WorkItemKind.SERVICE_REQUEST,
    status: WorkItemStatus.BLOCKED,
    priority: Priority.MEDIUM,
    dueDate: atNoonUtc("2026-07-04"),
    estimatedValueCents: 290000,
    customerId: "cust-greenfield-market",
    ownerId: "team-daniel-kim",
    notes: "Demo seed data: blocked overdue data-quality workflow.",
    createdAt: atNoonUtc("2026-06-28"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "work-summit-demo-account-audit",
    title: "Demo account audit",
    kind: WorkItemKind.SERVICE_REQUEST,
    status: WorkItemStatus.ACTIVE,
    priority: Priority.MEDIUM,
    dueDate: atNoonUtc("2026-07-18"),
    estimatedValueCents: 240000,
    customerId: "cust-summit-wireless-lab",
    ownerId: "team-ava-morgan",
    notes: "Demo seed data: internal account audit for technical support flow.",
    createdAt: atNoonUtc("2026-06-29"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "work-lakeside-quote-followup",
    title: "Quote follow-up package",
    kind: WorkItemKind.CAMPAIGN,
    status: WorkItemStatus.ACTIVE,
    priority: Priority.LOW,
    dueDate: atNoonUtc("2026-07-20"),
    estimatedValueCents: 150000,
    customerId: "cust-lakeside-events",
    ownerId: "team-sofia-patel",
    notes: "Demo seed data: low-priority prospect follow-up.",
    createdAt: atNoonUtc("2026-06-29"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "work-bluepeak-report-export",
    title: "Board report export setup",
    kind: WorkItemKind.SERVICE_REQUEST,
    status: WorkItemStatus.ACTIVE,
    priority: Priority.HIGH,
    dueDate: atNoonUtc("2026-07-11"),
    estimatedValueCents: 450000,
    customerId: "cust-bluepeak-nonprofit",
    ownerId: "team-olivia-chen",
    notes: "Demo seed data: reporting workflow for later CSV/export feature.",
    createdAt: atNoonUtc("2026-06-30"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "work-clearsky-onboarding-checklist",
    title: "Onboarding checklist closeout",
    kind: WorkItemKind.SERVICE_REQUEST,
    status: WorkItemStatus.COMPLETED,
    priority: Priority.MEDIUM,
    dueDate: atNoonUtc("2026-07-05"),
    completedAt: atNoonUtc("2026-07-05"),
    estimatedValueCents: 220000,
    customerId: "cust-clearsky-logistics",
    ownerId: "team-sofia-patel",
    notes: "Demo seed data: completed archived-customer work retained for reports.",
    createdAt: atNoonUtc("2026-06-30"),
    updatedAt: atNoonUtc("2026-07-05"),
  },
];

export const inventoryItems: Omit<Prisma.InventoryItemCreateManyInput, "workspaceId">[] = [
  {
    id: "inv-northstar-router-kit",
    name: "Northstar router kit",
    category: InventoryCategory.DEVICE,
    status: InventoryStatus.ASSIGNED,
    quantity: 1,
    lowStockThreshold: 0,
    location: "Toronto demo shelf A",
    referenceCode: "DEMO-DEV-001",
    customerId: "cust-northstar-outfitters",
    workItemId: "work-northstar-pos-device-rollout",
    ownerId: "team-ava-morgan",
    notes: "Demo seed data: assigned device kit for an overdue rollout.",
    createdAt: atNoonUtc("2026-06-20"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-northstar-tablet-pack",
    name: "Northstar tablet pack",
    category: InventoryCategory.DEVICE,
    status: InventoryStatus.RESERVED,
    quantity: 4,
    lowStockThreshold: 1,
    location: "Toronto demo shelf B",
    referenceCode: "DEMO-DEV-002",
    customerId: "cust-northstar-outfitters",
    workItemId: "work-northstar-spring-launch",
    ownerId: "team-ava-morgan",
    notes: "Demo seed data: reserved device inventory for campaign launch.",
    createdAt: atNoonUtc("2026-06-20"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-harborview-license-bundle",
    name: "Patient reminder license bundle",
    category: InventoryCategory.LICENSE,
    status: InventoryStatus.ASSIGNED,
    quantity: 12,
    lowStockThreshold: 3,
    location: "License vault",
    referenceCode: "DEMO-LIC-001",
    customerId: "cust-harborview-dental",
    workItemId: "work-harborview-license-renewal",
    ownerId: "team-marcus-reed",
    notes: "Demo seed data: assigned software licenses for renewal workflow.",
    createdAt: atNoonUtc("2026-06-21"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-cityline-kiosk-unit",
    name: "Membership kiosk unit",
    category: InventoryCategory.EQUIPMENT,
    status: InventoryStatus.ASSIGNED,
    quantity: 2,
    lowStockThreshold: 1,
    location: "Install bench",
    referenceCode: "DEMO-EQP-001",
    customerId: "cust-cityline-fitness",
    workItemId: "work-cityline-membership-kiosk",
    ownerId: "team-ava-morgan",
    notes: "Demo seed data: assigned hardware for customer installation.",
    createdAt: atNoonUtc("2026-06-21"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-brightpath-ad-creatives",
    name: "Enrollment ad creative set",
    category: InventoryCategory.MARKETING_ASSET,
    status: InventoryStatus.AVAILABLE,
    quantity: 18,
    lowStockThreshold: 5,
    location: "Shared asset library",
    referenceCode: "DEMO-MKT-001",
    customerId: "cust-brightpath-learning",
    workItemId: "work-brightpath-enrollment-campaign",
    ownerId: "team-marcus-reed",
    notes: "Demo seed data: marketing assets retained after campaign closeout.",
    createdAt: atNoonUtc("2026-06-22"),
    updatedAt: atNoonUtc("2026-07-06"),
  },
  {
    id: "inv-greenfield-barcode-scanners",
    name: "Barcode scanner pool",
    category: InventoryCategory.EQUIPMENT,
    status: InventoryStatus.LOW_STOCK,
    quantity: 1,
    lowStockThreshold: 4,
    location: "Warehouse bin 3",
    referenceCode: "DEMO-EQP-002",
    customerId: "cust-greenfield-market",
    workItemId: "work-greenfield-sku-cleanup",
    ownerId: "team-daniel-kim",
    notes: "Demo seed data: low-stock equipment for dashboard alert checks.",
    createdAt: atNoonUtc("2026-06-22"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-summit-test-phone-pool",
    name: "Wireless test phone pool",
    category: InventoryCategory.DEVICE,
    status: InventoryStatus.AVAILABLE,
    quantity: 8,
    lowStockThreshold: 2,
    location: "QA lab cabinet",
    referenceCode: "DEMO-DEV-003",
    customerId: "cust-summit-wireless-lab",
    workItemId: "work-summit-test-device-setup",
    ownerId: "team-ava-morgan",
    notes: "Demo seed data: device pool for technical test workflows.",
    createdAt: atNoonUtc("2026-06-23"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-lakeside-event-badges",
    name: "Event badge stock",
    category: InventoryCategory.SKU,
    status: InventoryStatus.RESERVED,
    quantity: 250,
    lowStockThreshold: 100,
    location: "Print room shelf",
    referenceCode: "DEMO-SKU-001",
    customerId: "cust-lakeside-events",
    workItemId: "work-lakeside-event-registration",
    ownerId: "team-sofia-patel",
    notes: "Demo seed data: reserved SKU stock for prospect event quote.",
    createdAt: atNoonUtc("2026-06-24"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-bluepeak-email-templates",
    name: "Donor email template set",
    category: InventoryCategory.MARKETING_ASSET,
    status: InventoryStatus.ASSIGNED,
    quantity: 6,
    lowStockThreshold: 2,
    location: "Shared asset library",
    referenceCode: "DEMO-MKT-002",
    customerId: "cust-bluepeak-nonprofit",
    workItemId: "work-bluepeak-donor-campaign",
    ownerId: "team-olivia-chen",
    notes: "Demo seed data: assigned campaign assets for urgent blocked work.",
    createdAt: atNoonUtc("2026-06-24"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-metro-printer-toner",
    name: "Printer toner reserve",
    category: InventoryCategory.SKU,
    status: InventoryStatus.LOW_STOCK,
    quantity: 2,
    lowStockThreshold: 8,
    location: "Supply cabinet",
    referenceCode: "DEMO-SKU-002",
    customerId: "cust-metro-print-studio",
    workItemId: "work-metro-print-reorder-portal",
    ownerId: "team-marcus-reed",
    notes: "Demo seed data: low-stock supply item for paused account context.",
    createdAt: atNoonUtc("2026-06-25"),
    updatedAt: atNoonUtc("2026-07-02"),
  },
  {
    id: "inv-clearsky-gps-test-units",
    name: "GPS test unit set",
    category: InventoryCategory.DEVICE,
    status: InventoryStatus.ASSIGNED,
    quantity: 5,
    lowStockThreshold: 2,
    location: "QA lab cabinet",
    referenceCode: "DEMO-DEV-004",
    customerId: "cust-clearsky-logistics",
    workItemId: "work-clearsky-route-dashboard",
    ownerId: "team-daniel-kim",
    notes: "Demo seed data: assigned test devices for route dashboard work.",
    createdAt: atNoonUtc("2026-06-25"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-demo-admin-seat",
    name: "Demo admin software seat",
    category: InventoryCategory.LICENSE,
    status: InventoryStatus.AVAILABLE,
    quantity: 3,
    lowStockThreshold: 1,
    location: "License vault",
    referenceCode: "DEMO-LIC-002",
    ownerId: "team-marcus-reed",
    notes: "Demo seed data: unassigned software seat for inventory availability.",
    createdAt: atNoonUtc("2026-06-26"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-qa-sandbox-accounts",
    name: "QA sandbox accounts",
    category: InventoryCategory.TEST_ACCOUNT,
    status: InventoryStatus.AVAILABLE,
    quantity: 10,
    lowStockThreshold: 3,
    location: "QA account registry",
    referenceCode: "DEMO-TST-001",
    ownerId: "team-daniel-kim",
    notes: "Demo seed data: available test accounts for QA workflows.",
    createdAt: atNoonUtc("2026-06-26"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-retired-router-batch",
    name: "Retired router batch",
    category: InventoryCategory.EQUIPMENT,
    status: InventoryStatus.RETIRED,
    quantity: 0,
    lowStockThreshold: 0,
    location: "Retired asset shelf",
    referenceCode: "DEMO-EQP-003",
    ownerId: "team-ava-morgan",
    notes: "Demo seed data: retired equipment for status filtering.",
    createdAt: atNoonUtc("2026-06-01"),
    updatedAt: atNoonUtc("2026-07-01"),
    archivedAt: atNoonUtc("2026-07-01"),
  },
  {
    id: "inv-wireless-sim-cards",
    name: "Wireless SIM cards",
    category: InventoryCategory.SKU,
    status: InventoryStatus.AVAILABLE,
    quantity: 40,
    lowStockThreshold: 10,
    location: "Secure drawer",
    referenceCode: "DEMO-SKU-003",
    ownerId: "team-ava-morgan",
    notes: "Demo seed data: available SKU inventory for future assignment flow.",
    createdAt: atNoonUtc("2026-06-27"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-asset-label-rolls",
    name: "Asset label rolls",
    category: InventoryCategory.SKU,
    status: InventoryStatus.LOW_STOCK,
    quantity: 3,
    lowStockThreshold: 15,
    location: "Supply cabinet",
    referenceCode: "DEMO-SKU-004",
    ownerId: "team-sofia-patel",
    notes: "Demo seed data: low-stock general supply item.",
    createdAt: atNoonUtc("2026-06-27"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-campaign-photo-set",
    name: "Campaign photo set",
    category: InventoryCategory.MARKETING_ASSET,
    status: InventoryStatus.AVAILABLE,
    quantity: 24,
    lowStockThreshold: 5,
    location: "Shared asset library",
    referenceCode: "DEMO-MKT-003",
    ownerId: "team-marcus-reed",
    notes: "Demo seed data: available creative inventory for campaigns.",
    createdAt: atNoonUtc("2026-06-28"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-support-laptop-loaner",
    name: "Support laptop loaner",
    category: InventoryCategory.DEVICE,
    status: InventoryStatus.RESERVED,
    quantity: 2,
    lowStockThreshold: 1,
    location: "Support cabinet",
    referenceCode: "DEMO-DEV-005",
    ownerId: "team-sofia-patel",
    notes: "Demo seed data: reserved internal support hardware.",
    createdAt: atNoonUtc("2026-06-28"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-brightpath-training-license",
    name: "Training platform license pack",
    category: InventoryCategory.LICENSE,
    status: InventoryStatus.ASSIGNED,
    quantity: 25,
    lowStockThreshold: 5,
    location: "License vault",
    referenceCode: "DEMO-LIC-003",
    customerId: "cust-brightpath-learning",
    workItemId: "work-brightpath-asset-handoff",
    ownerId: "team-marcus-reed",
    notes: "Demo seed data: assigned license pack for completed handoff.",
    createdAt: atNoonUtc("2026-06-29"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-clearsky-api-token-slot",
    name: "API token slot",
    category: InventoryCategory.SOFTWARE_ASSET,
    status: InventoryStatus.ASSIGNED,
    quantity: 1,
    lowStockThreshold: 1,
    location: "Secure credential registry",
    referenceCode: "DEMO-SFT-001",
    customerId: "cust-clearsky-logistics",
    workItemId: "work-clearsky-route-dashboard",
    ownerId: "team-daniel-kim",
    notes: "Demo seed data: assigned software asset for technical workflow.",
    createdAt: atNoonUtc("2026-06-29"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-cityline-member-cards",
    name: "Member card stock",
    category: InventoryCategory.SKU,
    status: InventoryStatus.AVAILABLE,
    quantity: 500,
    lowStockThreshold: 100,
    location: "Print room shelf",
    referenceCode: "DEMO-SKU-005",
    customerId: "cust-cityline-fitness",
    workItemId: "work-cityline-membership-kiosk",
    ownerId: "team-sofia-patel",
    notes: "Demo seed data: available customer-related stock.",
    createdAt: atNoonUtc("2026-06-30"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-greenfield-staging-database",
    name: "Staging database slot",
    category: InventoryCategory.SOFTWARE_ASSET,
    status: InventoryStatus.UNAVAILABLE,
    quantity: 1,
    lowStockThreshold: 0,
    location: "Internal platform registry",
    referenceCode: "DEMO-SFT-002",
    customerId: "cust-greenfield-market",
    workItemId: "work-greenfield-inventory-sync",
    ownerId: "team-ava-morgan",
    notes: "Demo seed data: unavailable software asset awaiting reset.",
    createdAt: atNoonUtc("2026-06-30"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-summit-device-cases",
    name: "Device case batch",
    category: InventoryCategory.EQUIPMENT,
    status: InventoryStatus.AVAILABLE,
    quantity: 15,
    lowStockThreshold: 4,
    location: "Warehouse bin 5",
    referenceCode: "DEMO-EQP-004",
    customerId: "cust-summit-wireless-lab",
    workItemId: "work-summit-test-device-setup",
    ownerId: "team-ava-morgan",
    notes: "Demo seed data: available device accessories.",
    createdAt: atNoonUtc("2026-07-01"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "inv-bluepeak-report-template",
    name: "Board report template",
    category: InventoryCategory.MARKETING_ASSET,
    status: InventoryStatus.RESERVED,
    quantity: 2,
    lowStockThreshold: 1,
    location: "Shared asset library",
    referenceCode: "DEMO-MKT-004",
    customerId: "cust-bluepeak-nonprofit",
    workItemId: "work-bluepeak-report-export",
    ownerId: "team-olivia-chen",
    notes: "Demo seed data: reserved reporting asset for export workflow.",
    createdAt: atNoonUtc("2026-07-01"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
];

export const issues: Omit<Prisma.IssueCreateManyInput, "workspaceId">[] = [
  {
    id: "issue-northstar-device-delay",
    title: "Device shipment delay",
    category: IssueCategory.FULFILLMENT,
    priority: Priority.URGENT,
    status: IssueStatus.OPEN,
    description: "Demo seed data: router kit shipment is late for an overdue device rollout.",
    customerId: "cust-northstar-outfitters",
    workItemId: "work-northstar-pos-device-rollout",
    ownerId: "team-sofia-patel",
    createdAt: atNoonUtc("2026-07-02"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-northstar-pos-auth",
    title: "POS auth callback mismatch",
    category: IssueCategory.BUG,
    priority: Priority.HIGH,
    status: IssueStatus.IN_PROGRESS,
    description: "Demo seed data: QA found callback mismatch while testing POS authentication.",
    customerId: "cust-northstar-outfitters",
    workItemId: "work-northstar-pos-device-rollout",
    ownerId: "team-daniel-kim",
    createdAt: atNoonUtc("2026-07-03"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-harborview-copy-approval",
    title: "Reminder copy approval missing",
    category: IssueCategory.BLOCKER,
    priority: Priority.HIGH,
    status: IssueStatus.BLOCKED,
    description: "Demo seed data: customer approval is blocking patient reminder workflow.",
    customerId: "cust-harborview-dental",
    workItemId: "work-harborview-patient-reminders",
    ownerId: "team-marcus-reed",
    createdAt: atNoonUtc("2026-07-04"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-cityline-kiosk-timeout",
    title: "Kiosk session timeout too short",
    category: IssueCategory.BUG,
    priority: Priority.HIGH,
    status: IssueStatus.OPEN,
    description: "Demo seed data: kiosk logs users out too quickly during membership flow.",
    customerId: "cust-cityline-fitness",
    workItemId: "work-cityline-membership-kiosk",
    ownerId: "team-daniel-kim",
    createdAt: atNoonUtc("2026-07-04"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-brightpath-final-assets",
    title: "Final asset package confirmed",
    category: IssueCategory.SUPPORT_REQUEST,
    priority: Priority.MEDIUM,
    status: IssueStatus.RESOLVED,
    description: "Demo seed data: support request to confirm BrightPath final asset delivery.",
    resolutionNotes: "Demo seed data: asset package confirmed and handoff completed.",
    resolvedAt: atNoonUtc("2026-07-06"),
    customerId: "cust-brightpath-learning",
    workItemId: "work-brightpath-asset-handoff",
    ownerId: "team-sofia-patel",
    createdAt: atNoonUtc("2026-07-05"),
    updatedAt: atNoonUtc("2026-07-06"),
  },
  {
    id: "issue-greenfield-sku-mismatch",
    title: "SKU export mismatch",
    category: IssueCategory.DATA_QUALITY,
    priority: Priority.HIGH,
    status: IssueStatus.BLOCKED,
    description: "Demo seed data: SKU export does not match the latest barcode sheet.",
    customerId: "cust-greenfield-market",
    workItemId: "work-greenfield-sku-cleanup",
    ownerId: "team-daniel-kim",
    createdAt: atNoonUtc("2026-07-05"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-summit-imei-list",
    title: "IMEI list needs validation",
    category: IssueCategory.DATA_QUALITY,
    priority: Priority.MEDIUM,
    status: IssueStatus.IN_PROGRESS,
    description: "Demo seed data: test phone list needs QA validation before setup.",
    customerId: "cust-summit-wireless-lab",
    workItemId: "work-summit-test-device-setup",
    ownerId: "team-daniel-kim",
    createdAt: atNoonUtc("2026-07-05"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-lakeside-contract-question",
    title: "Event registration scope question",
    category: IssueCategory.SUPPORT_REQUEST,
    priority: Priority.LOW,
    status: IssueStatus.OPEN,
    description: "Demo seed data: prospect asked whether badge printing is included.",
    customerId: "cust-lakeside-events",
    workItemId: "work-lakeside-event-registration",
    ownerId: "team-sofia-patel",
    createdAt: atNoonUtc("2026-07-05"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-bluepeak-donor-segment",
    title: "Donor segment file blocked",
    category: IssueCategory.DATA_QUALITY,
    priority: Priority.URGENT,
    status: IssueStatus.BLOCKED,
    description: "Demo seed data: campaign cannot proceed until donor segment columns are fixed.",
    customerId: "cust-bluepeak-nonprofit",
    workItemId: "work-bluepeak-donor-campaign",
    ownerId: "team-olivia-chen",
    createdAt: atNoonUtc("2026-07-01"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-metro-print-scope-change",
    title: "Portal scope change cancelled",
    category: IssueCategory.SUPPORT_REQUEST,
    priority: Priority.MEDIUM,
    status: IssueStatus.CLOSED,
    description: "Demo seed data: paused customer cancelled the reorder portal cleanup.",
    resolutionNotes: "Demo seed data: closed because the related work item was cancelled.",
    resolvedAt: atNoonUtc("2026-07-02"),
    customerId: "cust-metro-print-studio",
    workItemId: "work-metro-print-reorder-portal",
    ownerId: "team-marcus-reed",
    createdAt: atNoonUtc("2026-06-30"),
    updatedAt: atNoonUtc("2026-07-02"),
  },
  {
    id: "issue-clearsky-map-widget",
    title: "Route map widget flicker",
    category: IssueCategory.BUG,
    priority: Priority.HIGH,
    status: IssueStatus.IN_PROGRESS,
    description: "Demo seed data: route widget flickers during filter changes.",
    customerId: "cust-clearsky-logistics",
    workItemId: "work-clearsky-route-dashboard",
    ownerId: "team-ava-morgan",
    createdAt: atNoonUtc("2026-07-03"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-harborview-license-key",
    title: "License key confirmation needed",
    category: IssueCategory.FULFILLMENT,
    priority: Priority.MEDIUM,
    status: IssueStatus.OPEN,
    description: "Demo seed data: renewal pack needs a license key confirmation.",
    customerId: "cust-harborview-dental",
    workItemId: "work-harborview-license-renewal",
    ownerId: "team-marcus-reed",
    createdAt: atNoonUtc("2026-07-06"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-cityline-qa-retest",
    title: "Kiosk QA retest requested",
    category: IssueCategory.BUG,
    priority: Priority.MEDIUM,
    status: IssueStatus.OPEN,
    description: "Demo seed data: QA requested a retest after kiosk configuration update.",
    customerId: "cust-cityline-fitness",
    workItemId: "work-cityline-qa-bug-bash",
    ownerId: "team-daniel-kim",
    createdAt: atNoonUtc("2026-07-06"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-brightpath-signoff",
    title: "BrightPath signoff recorded",
    category: IssueCategory.SUPPORT_REQUEST,
    priority: Priority.LOW,
    status: IssueStatus.CLOSED,
    description: "Demo seed data: customer confirmed final training asset signoff.",
    resolutionNotes: "Demo seed data: signoff recorded and work item completed.",
    resolvedAt: atNoonUtc("2026-07-07"),
    customerId: "cust-brightpath-learning",
    workItemId: "work-brightpath-asset-handoff",
    ownerId: "team-marcus-reed",
    createdAt: atNoonUtc("2026-07-07"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-greenfield-missing-barcodes",
    title: "Missing barcode labels",
    category: IssueCategory.FULFILLMENT,
    priority: Priority.HIGH,
    status: IssueStatus.OPEN,
    description: "Demo seed data: barcode label rolls are below threshold for SKU cleanup.",
    customerId: "cust-greenfield-market",
    workItemId: "work-greenfield-sku-cleanup",
    ownerId: "team-sofia-patel",
    createdAt: atNoonUtc("2026-07-06"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-summit-demo-login",
    title: "Demo login reset completed",
    category: IssueCategory.BUG,
    priority: Priority.MEDIUM,
    status: IssueStatus.RESOLVED,
    description: "Demo seed data: demo account reset was needed before device testing.",
    resolutionNotes: "Demo seed data: account was reset and QA verified access.",
    resolvedAt: atNoonUtc("2026-07-06"),
    customerId: "cust-summit-wireless-lab",
    workItemId: "work-summit-demo-account-audit",
    ownerId: "team-ava-morgan",
    createdAt: atNoonUtc("2026-07-05"),
    updatedAt: atNoonUtc("2026-07-06"),
  },
  {
    id: "issue-bluepeak-export-columns",
    title: "Report export columns need review",
    category: IssueCategory.SUPPORT_REQUEST,
    priority: Priority.HIGH,
    status: IssueStatus.IN_PROGRESS,
    description: "Demo seed data: board report export needs readable column names.",
    customerId: "cust-bluepeak-nonprofit",
    workItemId: "work-bluepeak-report-export",
    ownerId: "team-olivia-chen",
    createdAt: atNoonUtc("2026-07-06"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-clearsky-import-validation",
    title: "Route import validation warning",
    category: IssueCategory.DATA_QUALITY,
    priority: Priority.HIGH,
    status: IssueStatus.OPEN,
    description: "Demo seed data: route import warning needs review before handoff.",
    customerId: "cust-clearsky-logistics",
    workItemId: "work-clearsky-route-dashboard",
    ownerId: "team-daniel-kim",
    createdAt: atNoonUtc("2026-07-06"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-inventory-low-scanners",
    title: "Scanner inventory below threshold",
    category: IssueCategory.FULFILLMENT,
    priority: Priority.URGENT,
    status: IssueStatus.OPEN,
    description: "Demo seed data: barcode scanner pool is below the low-stock threshold.",
    customerId: "cust-greenfield-market",
    workItemId: "work-greenfield-sku-cleanup",
    ownerId: "team-sofia-patel",
    createdAt: atNoonUtc("2026-07-07"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-demo-report-empty-state",
    title: "Report empty-state copy review",
    category: IssueCategory.OTHER,
    priority: Priority.LOW,
    status: IssueStatus.OPEN,
    description: "Demo seed data: internal task to review reporting empty-state wording later.",
    ownerId: "team-daniel-kim",
    createdAt: atNoonUtc("2026-07-07"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-northstar-training-schedule",
    title: "Training schedule not confirmed",
    category: IssueCategory.SUPPORT_REQUEST,
    priority: Priority.MEDIUM,
    status: IssueStatus.OPEN,
    description: "Demo seed data: support training date is not confirmed for Northstar.",
    customerId: "cust-northstar-outfitters",
    workItemId: "work-northstar-support-refresh",
    ownerId: "team-sofia-patel",
    createdAt: atNoonUtc("2026-07-07"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-lakeside-email-domain",
    title: "Email domain pending confirmation",
    category: IssueCategory.DATA_QUALITY,
    priority: Priority.MEDIUM,
    status: IssueStatus.OPEN,
    description: "Demo seed data: prospect has not confirmed preferred sender domain.",
    customerId: "cust-lakeside-events",
    workItemId: "work-lakeside-quote-followup",
    ownerId: "team-sofia-patel",
    createdAt: atNoonUtc("2026-07-07"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-summit-device-case-shortage",
    title: "Device cases may not cover test pool",
    category: IssueCategory.FULFILLMENT,
    priority: Priority.HIGH,
    status: IssueStatus.BLOCKED,
    description: "Demo seed data: accessory count needs confirmation before test device setup.",
    customerId: "cust-summit-wireless-lab",
    workItemId: "work-summit-test-device-setup",
    ownerId: "team-ava-morgan",
    createdAt: atNoonUtc("2026-07-07"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "issue-clearsky-route-owner",
    title: "Route owner confirmed",
    category: IssueCategory.BLOCKER,
    priority: Priority.URGENT,
    status: IssueStatus.RESOLVED,
    description: "Demo seed data: route dashboard owner was missing for handoff.",
    resolutionNotes: "Demo seed data: owner confirmed and handoff checklist updated.",
    resolvedAt: atNoonUtc("2026-07-07"),
    customerId: "cust-clearsky-logistics",
    workItemId: "work-clearsky-onboarding-checklist",
    ownerId: "team-olivia-chen",
    createdAt: atNoonUtc("2026-07-06"),
    updatedAt: atNoonUtc("2026-07-07"),
  },
];

export const activityEvents: Omit<Prisma.ActivityEventCreateManyInput, "workspaceId">[] = [
  {
    id: "activity-northstar-rollout-created",
    action: ActivityAction.CREATED,
    summary: "Demo seed data: POS device rollout created for Northstar.",
    metadata: { source: "demo-seed", module: "work-items" },
    actorId: "team-marcus-reed",
    customerId: "cust-northstar-outfitters",
    workItemId: "work-northstar-pos-device-rollout",
    createdAt: atNoonUtc("2026-06-19"),
  },
  {
    id: "activity-northstar-delay-opened",
    action: ActivityAction.CREATED,
    summary: "Demo seed data: urgent device shipment issue opened.",
    metadata: { source: "demo-seed", module: "issues" },
    actorId: "team-sofia-patel",
    customerId: "cust-northstar-outfitters",
    workItemId: "work-northstar-pos-device-rollout",
    issueId: "issue-northstar-device-delay",
    createdAt: atNoonUtc("2026-07-02"),
  },
  {
    id: "activity-harborview-blocked",
    action: ActivityAction.STATUS_CHANGED,
    summary: "Demo seed data: patient reminder workflow marked blocked.",
    metadata: { from: "ACTIVE", to: "BLOCKED", source: "demo-seed" },
    actorId: "team-sofia-patel",
    customerId: "cust-harborview-dental",
    workItemId: "work-harborview-patient-reminders",
    issueId: "issue-harborview-copy-approval",
    createdAt: atNoonUtc("2026-07-04"),
  },
  {
    id: "activity-brightpath-completed",
    action: ActivityAction.STATUS_CHANGED,
    summary: "Demo seed data: BrightPath enrollment campaign completed.",
    metadata: { from: "ACTIVE", to: "COMPLETED", source: "demo-seed" },
    actorId: "team-marcus-reed",
    customerId: "cust-brightpath-learning",
    workItemId: "work-brightpath-enrollment-campaign",
    createdAt: atNoonUtc("2026-07-06"),
  },
  {
    id: "activity-greenfield-low-stock",
    action: ActivityAction.UPDATED,
    summary: "Demo seed data: barcode scanner pool marked low stock.",
    metadata: { quantity: 1, lowStockThreshold: 4, source: "demo-seed" },
    actorId: "team-daniel-kim",
    customerId: "cust-greenfield-market",
    workItemId: "work-greenfield-sku-cleanup",
    inventoryItemId: "inv-greenfield-barcode-scanners",
    createdAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "activity-summit-devices-assigned",
    action: ActivityAction.ASSIGNED,
    summary: "Demo seed data: wireless test phone pool assigned to Summit work.",
    metadata: { source: "demo-seed", module: "inventory" },
    actorId: "team-ava-morgan",
    customerId: "cust-summit-wireless-lab",
    workItemId: "work-summit-test-device-setup",
    inventoryItemId: "inv-summit-test-phone-pool",
    createdAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "activity-bluepeak-blocked",
    action: ActivityAction.STATUS_CHANGED,
    summary: "Demo seed data: donor campaign marked blocked by data-quality issue.",
    metadata: { from: "ACTIVE", to: "BLOCKED", source: "demo-seed" },
    actorId: "team-olivia-chen",
    customerId: "cust-bluepeak-nonprofit",
    workItemId: "work-bluepeak-donor-campaign",
    issueId: "issue-bluepeak-donor-segment",
    createdAt: atNoonUtc("2026-07-01"),
  },
  {
    id: "activity-metro-cancelled",
    action: ActivityAction.STATUS_CHANGED,
    summary: "Demo seed data: Metro Print reorder portal cancelled.",
    metadata: { from: "ACTIVE", to: "CANCELLED", source: "demo-seed" },
    actorId: "team-marcus-reed",
    customerId: "cust-metro-print-studio",
    workItemId: "work-metro-print-reorder-portal",
    issueId: "issue-metro-print-scope-change",
    createdAt: atNoonUtc("2026-07-02"),
  },
  {
    id: "activity-clearsky-route-update",
    action: ActivityAction.UPDATED,
    summary: "Demo seed data: route dashboard handoff updated after validation warning.",
    metadata: { source: "demo-seed", module: "work-items" },
    actorId: "team-daniel-kim",
    customerId: "cust-clearsky-logistics",
    workItemId: "work-clearsky-route-dashboard",
    issueId: "issue-clearsky-import-validation",
    createdAt: atNoonUtc("2026-07-07"),
  },
  {
    id: "activity-brightpath-asset-resolved",
    action: ActivityAction.RESOLVED,
    summary: "Demo seed data: BrightPath final asset issue resolved.",
    metadata: { source: "demo-seed", module: "issues" },
    actorId: "team-sofia-patel",
    customerId: "cust-brightpath-learning",
    workItemId: "work-brightpath-asset-handoff",
    issueId: "issue-brightpath-final-assets",
    createdAt: atNoonUtc("2026-07-06"),
  },
  {
    id: "activity-retired-router-archived",
    action: ActivityAction.ARCHIVED,
    summary: "Demo seed data: retired router batch archived.",
    metadata: { source: "demo-seed", module: "inventory" },
    actorId: "team-ava-morgan",
    inventoryItemId: "inv-retired-router-batch",
    createdAt: atNoonUtc("2026-07-01"),
  },
  {
    id: "activity-demo-report-task-created",
    action: ActivityAction.CREATED,
    summary: "Demo seed data: reporting empty-state review task created.",
    metadata: { source: "demo-seed", module: "issues" },
    actorId: "team-daniel-kim",
    issueId: "issue-demo-report-empty-state",
    createdAt: atNoonUtc("2026-07-07"),
  },
];

export const demoSeedIds = {
  teamMembers: collectSeedIds(teamMembers),
  customers: collectSeedIds(customers),
  workItems: collectSeedIds(workItems),
  inventoryItems: collectSeedIds(inventoryItems),
  issues: collectSeedIds(issues),
  activityEvents: collectSeedIds(activityEvents),
};

export const demoSeedCounts = {
  teamMembers: teamMembers.length,
  customers: customers.length,
  workItems: workItems.length,
  inventoryItems: inventoryItems.length,
  issues: issues.length,
  activityEvents: activityEvents.length,
};
